// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRKdJxNkoOjtn8d0cGdeajc6yNx-zEPc',
    appId: '1:456362499:web:515437e7105698542edc36',
    messagingSenderId: '456362499',
    projectId: 'tender-e0fd7',
    authDomain: 'tender-e0fd7.firebaseapp.com',
    storageBucket: 'tender-e0fd7.firebasestorage.app',
    measurementId: 'G-RYQEXY6HGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaa9CbyYv8mRbSYwWUhOXtpPG_tokoJ3s',
    appId: '1:456362499:android:5ffd28c46d1d0c552edc36',
    messagingSenderId: '456362499',
    projectId: 'tender-e0fd7',
    storageBucket: 'tender-e0fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_US2y2RpoqHwZbYtqcGN2A0z9LfZemik',
    appId: '1:456362499:ios:624430b7f42b59962edc36',
    messagingSenderId: '456362499',
    projectId: 'tender-e0fd7',
    storageBucket: 'tender-e0fd7.firebasestorage.app',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_US2y2RpoqHwZbYtqcGN2A0z9LfZemik',
    appId: '1:456362499:ios:624430b7f42b59962edc36',
    messagingSenderId: '456362499',
    projectId: 'tender-e0fd7',
    storageBucket: 'tender-e0fd7.firebasestorage.app',
    iosBundleId: 'com.example.tender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpRKdJxNkoOjtn8d0cGdeajc6yNx-zEPc',
    appId: '1:456362499:web:3f2e91af9e38483f2edc36',
    messagingSenderId: '456362499',
    projectId: 'tender-e0fd7',
    authDomain: 'tender-e0fd7.firebaseapp.com',
    storageBucket: 'tender-e0fd7.firebasestorage.app',
    measurementId: 'G-QZJGGV59LX',
  );

}